use_frameworks!

target 'ZYLint_Example' do
  pod 'ZYLint', :path => '../'

  target 'ZYLint_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
end
